-- DATE - YYYY-MM-DD
-- Timestamp - YYYY-MM-DD HH:MM:SS (ISO)
-- UTC (timwstmap with timezone) - YYYY-MM-DD HH:MM:SS+HH 
-- INTERVAL
-- HUMAN UNDERSTANDERABLE FORMAT
-- POSTGRE special
-- '2010-01-01::date + 1'
-- '2018-12-10'::date + '1 year'::interval